[package]
name = "hielke_advent_of_code_2021_rust"
version = "0.1.0"
authors = ["Hielke van Buren <hielkevanburen@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.3.1"
regex = "1.4.2"